<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    public function getStock($stockCode,$exchangeCode){
        $dql="SELECT stock FROM AppBundle\Entity\Stock stock JOIN stock.exchange exchange WHERE stock.stockCode='$stockCode' AND exchange.code='$exchangeCode' ";
        $query = $this->getEntityManager()->createQuery($dql)->setMaxResults(1);
        $result=$query->getResult()[0];
        return $result;
    }

    public function getStatus($stockCode,$exchangeCode)
    {
        $dql="SELECT status FROM AppBundle\Entity\Stock stock JOIN stock.exchange exchange WHERE stock.stockCode='$stockCode' AND exchange.code='$exchangeCode' ";
        $query = $this->getEntityManager()->createQuery($dql)->setMaxResults(1);
        $result=$query->getResult()[0];
        return $result;
    }

    public function checkUsers($stockId){
        $dql="SELECT user FROM AppBundle\Entity\User user JOIN user.stocks stock WHERE stock.id='$stockId'";
        $query = $this->getEntityManager()->createQuery($dql);
        $result=$query->getResult();
        return $result;
    }

    public function getStockList($exchangeCode){
        $dql="SELECT stock FROM AppBundle\Entity\Stock stock JOIN stock.exchange exchange WHERE stock.status='1' AND exchange.code='$exchangeCode' ";
        $query = $this->getEntityManager()->createQuery($dql);
        $result=$query->getResult();
        return $result;
    }
}
